name: unit-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ['v*']

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.41.4
          manifest-path: pyproject.toml

      - name: Run unit tests
        run: pixi run test

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        if: github.actor != 'dependabot[bot]'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build conda package
        run: pixi run conda-build
