name: unit-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ['v*']

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.41.4
          manifest-path: pyproject.toml
      - name: run unit tests
        run: |
          echo "running unit tests"
          pixi run test
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v5
        if: github.actor != 'dependabot[bot]'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: build conda package
        run: |
          echo "build conda package"
          pixi run build-conda
